username:               "janc"
port:                   22
look_for_keys:          True
key_filename:           "/home/aiida/.ssh/aiida"
timeout:                60
allow_agent:            True
proxy_jump:             ""
proxy_command:          ""
compress:               True
gss_auth:               False
gss_kex:                False
gss_deleg_creds:        False
gss_host:               "unity.sintef.no"
load_system_host_keys:  True
key_policy:             "AutoAddPolicy"
use_login_shell:        True
safe_interval:          30.0
