username:               "kurianv"
port:                   22
look_for_keys:          True
key_filename: ""
timeout:                60
allow_agent:            True
proxy_jump:             "kurianv@unity-gpu-01.sintef.no"
proxy_command: ""
compress:               True
gss_auth:               False
gss_kex:                False
gss_deleg_creds:        False
gss_host:               "unity2.sintef.no"
load_system_host_keys:  True
key_policy:             "AutoAddPolicy"
use_login_shell:        True
safe_interval:          30.0
